#
# Module manifest for module 'mdatp-pwsh'
#
# Generated by: Tim Small
#
# Generated on: 7/25/2020
#

@{

    RootModule         = "MdatpPwsh.dll"
    ModuleVersion      = "2021.01.00"

    CompatiblePSEditions = @(
        "Desktop",
        "Core"
    )

    GUID               = "afc0e191-ffe7-4261-ba9e-d59652423d8c"
    Author             = "Timothy Small"
    CompanyName        = "Smalls.Online"
    Copyright          = "2021 Timothy Small"
    Description        = "Defender for Endpoint PowerShell Module"

    PowerShellVersion = "5.1"
    PowerShellHostVersion = "5.1"
    # PowerShellHostName = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()

    RequiredAssemblies = @(
        "Microsoft.Identity.Client.dll",
        "System.Text.Json.dll"
    )

    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # FunctionsToExport  = "*"

    CmdletsToExport    = @(
        "Set-DatpModuleConfig",
        "Connect-DatpGraph",
        "Get-DatpSessionClient",
        "Get-DatpMachine", 
        "Get-DatpMachineAlerts",
        "Get-DatpMachineUsers",
        "Set-DatpMachineIsolation",
        "Add-DatpMachineTag", 
        "Remove-DatpMachineTag",
        "Start-DatpMachineScan", 
        "Get-DatpMachineAction",
        "Start-DatpInvestigationPkgCollection", 
        "Get-DatpDomainStats",
        "Get-DatpDomainRelated", 
        "Get-DatpUserMachines",
        "Get-DatpUserAlerts",
        "Get-DatpAlert", 
        "Update-DatpAlert",
        "Out-DatpInvestigationPkg",
        "Get-DatpFile",
        "Get-DatpFileAlerts",
        "Get-DatpFileMachines",
        "Get-DatpFileStats"
    )

    # VariablesToExport  = "*"

    # AliasesToExport    = "*"

    # DscResourcesToExport = @()
    # ModuleList = @()

    FileList = @(
        "License.txt",
        "MdatpPwsh.dll",
        "MdatpPwsh.dll-Help.xml",
        "Microsoft.Identity.Client.dll",
        "System.Text.Json.dll"
    )

    PrivateData        = @{

        PSData = @{

            Tags = @(
                "Defender-ATP",
                "Defender-for-Endpoint"
            )

            LicenseUri = "https://raw.githubusercontent.com/Smalls1652/mdatp-pwsh/stable/license.txt"

            ProjectUri = "https://github.com/Smalls1652/mdatp-pwsh"

            # IconUri = ''

            # ReleaseNotes = ''

            # Prerelease = ""

            RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}

