#
# Module manifest for module 'mdatp-pwsh'
#
# Generated by: Tim Small
#
# Generated on: 7/25/2020
#

@{

    RootModule         = "MdatpPwsh.dll"
    ModuleVersion      = "2020.7.1"
    # CompatiblePSEditions = @()
    GUID               = "afc0e191-ffe7-4261-ba9e-d59652423d8c"
    Author             = "Tim Small"
    CompanyName        = "Smalls.Online"
    Copyright          = "2020"
    Description        = "MDATP PowerShell Module"
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    RequiredAssemblies = "Microsoft.Identity.Client.dll", "Newtonsoft.Json.dll"
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    FunctionsToExport  = "*"

    CmdletsToExport    = @(
        "Set-DatpModuleConfig",
        "Connect-DatpGraph",
        "Get-DatpMachine", 
        "Get-DatpMachineAlerts",
        "Get-DatpMachineUsers", 
        "Set-DatpMachineIsolation",
        "Add-DatpMachineTag", 
        "Remove-DatpMachineTag",
        "Start-DatpMachineScan", 
        "Get-DatpMachineAction",
        "Start-DatpInvestigationPkgCollection", 
        "Get-DatpDomainStats",
        "Get-DatpDomainRelated", 
        "Get-DatpUserMachines",
        "Get-DatpUserAlerts",
        "Get-DatpAlert", 
        "Update-DatpAlert",
        "Out-DatpInvestigationPkg"
    )

    VariablesToExport  = "*"

    AliasesToExport    = "*"

    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()

    PrivateData        = @{

        PSData = @{

            # Tags = @()

            LicenseUri = "https://raw.githubusercontent.com/Smalls1652/mdatp-pwsh/master/license.txt"

            ProjectUri = "https://github.com/smalls1652/mdatp-pwsh"

            # IconUri = ''

            # ReleaseNotes = ''

            Prerelease = "alpha2"

            RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}

