# This is a basic workflow to help you get started with Actions

name: Run Weekly Dev Build
 
on:
  schedule:
  - cron: "0 0 * * 6"

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        
      - name: Install platyPS
        run: Install-Module -Name "platyPS" -Force
        shell: pwsh

      - name: Run build script
        run: ./BuildModule.ps1
        shell: pwsh
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: mdatp-pwsh-dev
          path: ./build/mdatp-pwsh
